# Generated by Django 4.2.6 on 2023-10-28 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_myuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(choices=[('0', 'Land'), ('1', 'Flat'), ('2', 'House'), ('3', 'Farm')], max_length=2)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('amenities', models.JSONField()),
                ('date_avail', models.DateField()),
                ('sellor_lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
