# Generated by Django 4.2.6 on 2023-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_property_sellor_lessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
