# Generated by Django 4.2.6 on 2023-11-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_myuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contract_type',
            field=models.CharField(choices=[('0', 'Rent'), ('1', 'Sell')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
