# Generated by Django 4.2.6 on 2023-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_myuser_admin_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='no_reports',
            field=models.IntegerField(default=0),
        ),
    ]
