# Generated by Django 4.2.6 on 2023-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_myuser_no_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='no_reports',
        ),
        migrations.AddField(
            model_name='myuser',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
